# Generated by Django 4.0.3 on 2022-03-12 19:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contour_id', models.IntegerField(verbose_name='Kontur raqami')),
                ('area', models.FloatField(blank=True, null=True, verbose_name='Maydoni')),
                ('crop', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ekin turi')),
                ('crop_plan', models.FloatField(blank=True, null=True, verbose_name='Rejadagi ekin maydoni')),
                ('crop_real', models.FloatField(blank=True, null=True, verbose_name='Amaldagi ekin maydoni')),
                ('farm_name', models.CharField(max_length=255, verbose_name='FX nomi')),
                ('farm_id', models.IntegerField(verbose_name='FX raqami')),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=3857, verbose_name='Geometry')),
            ],
            options={
                'verbose_name': 'Kontur ',
                'verbose_name_plural': 'Konturlar',
            },
        ),
    ]
